Add nginx-php service
joshminnie/workspace pull request #19
Opened 2021-11-18 15:09 UTC by joshpennington

Resolves #18

This adds a container that is useful for running an nginx server will many versions of PHP available to it. This container is more complex than other so I have added a Readme file to explain how to get this setup.

2021-11-20 23:53 UTC, joshminnie requested changes

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php54/Dockerfile
> +RUN if [[ -f "/scripts/build.sh" ]]; then sh /scripts/build.sh ; fi
Please add blank line at EOF. Consider configuring your editor to do so on save.

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/Readme.md
> +# nginx and Multiple PHP Versions
Change the name of the file to `README.md`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/Readme.md
> +```server {
GitHub Markdown formatting error.

This should be broken out to separate lines. If you have the syntax that you'd like highlighted, that would be on that same line.

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/default.conf.example
> +server {
Change file name to `default.sample.conf`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/nginx.conf.example
> +user  nginx;
Change file name to `nginx.sample.conf`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php54/build.sh.example
> +#! /bin/bash
Change to file name to `build.sample.sh`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php55/build.sh.example
> +#! /bin/bash
Change file name to `build.sample.sh`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php72/build.sh.example
> +#! /bin/bash
Change file name to `build.sample.sh`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php72/Dockerfile
> +RUN if [[ -f "/scripts/build.sh" ]]; then sh /scripts/build.sh ; fi
Add blank line at EOF. Consider configuring your editor to handle that automatically for you on save, if you are not already using VS Code.

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php71/build.sh.example
> +#! /bin/bash
Change file name to `build.sample.sh`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php71/Dockerfile
> +RUN if [[ -f "/scripts/build.sh" ]]; then sh /scripts/build.sh ; fi
Add blank line at EOF. Consider configuring your editor to handle that automatically for you on save, if you are not already using VS Code.

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php70/build.sh.example
> +#! /bin/bash
Change file name to `build.sample.sh`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php70/Dockerfile
> +RUN if [[ -f "/scripts/build.sh" ]]; then sh /scripts/build.sh ; fi
Add blank line at EOF. Consider configuring your editor to handle that automatically for you on save, if you are not already using VS Code.

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php56/build.sh.example
> +#! /bin/bash
Change file name to `build.sample.sh`.

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php80/build.sh.example
> +#! /bin/bash
Rename file to `build.sample.sh`

2021-11-20 23:53 UTC, joshminnie commented on services/nginxphp/php74/build.sh.example
> +#! /bin/bash
Rename file to `build.sample.sh`

2021-11-21 03:09 UTC, joshpennington commented
@joshminnie All the requested changes have been completed.

2021-11-21 17:32 UTC, joshminnie approved these changes

2021-11-21 17:32 UTC, merged